### ISSUE TITLE
pull request builds from other repos error on travis

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#447]
see https://travis-ci.org/WikiEducationFoundation/WikiEduDashboard/builds/88644239

**Comment by bmathews** [comment]
Fixed via https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/459

**Comment by ragesoss** [comment]
PRs from other repos still fail, but at a different step now: https://travis-ci.org/WikiEducationFoundation/WikiEduDashboard/jobs/93908067

**Comment by bmathews** [comment]
I can't really tell what's happening from that error log. Anyone else have ideas?

**Comment by ragesoss** [comment]
Ah! I bet the private env variables on travis aren't added for PRs from other repos, because then anybody could write a script into PR that read and published those secrets.

**Comment by ragesoss** [comment]
So, the build would be failing because the sentry url is nil. Maybe we set the sentry url to some dummy url if it's not defined, so then the build process wouldn't choke there. Sentry won't get triggered anyway in the test environment, it just needs to get past that point in the build.
