### ISSUE TITLE
Directory permissions error prevents syllabus upload

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#842]
I tried to upload a syllabus on staging, and hit an error.

See https://sentry.wikiedu.org/wikiedu/staging/issues/573/

Perhaps we need to change the target directory and/or add another symlink to the Capistrano config?

cc @thenickcox

**Comment by thenickcox** [comment]
I think we can just `chmod` the directory. This version of paperclip is configured to store the files in a place that survives deployments by default.

**Comment by ragesoss** [comment]
> on standard Capistrano deployments, the public/system directory is symlinked to the app's shared directory

I don't think we've got it configured that way; there's no `public` in the shared directory.

**Comment by thenickcox** [comment]
Should be fixed via 345dca0, according to [this issue](https://github.com/capistrano/rails/issues/27).

**Comment by ragesoss** [comment]
@thenickcox it was still not working. I had to do `chmod 777 system` within that shared public directory before it would work.
